const NAME_LOOKUP: Record<string, string> = {
  aaron: "אהרון", abel: "הבל", abigail: "אביגיל", abraham: "אברהם",
  adam: "אדם", adina: "אדינה", alon: "אלון", amir: "אמיר",
  amit: "עמית", anat: "ענת", ari: "ארי", ariel: "אריאל",
  asher: "אשר", avi: "אבי", avigail: "אביגיל", avital: "אביטל",
  avraham: "אברהם",
  bar: "בר", baruch: "ברוך", bat: "בת", batya: "בתיה",
  becca: "רבקה", benjamin: "בנימין", ben: "בן",
  caleb: "כלב", carmel: "כרמל", carmi: "כרמי",
  dan: "דן", dana: "דנה", daniel: "דניאל", dani: "דני",
  daphna: "דפנה", david: "דוד", debbie: "דבורה", deborah: "דבורה",
  devorah: "דבורה", dina: "דינה", dorit: "דורית", doron: "דורון",
  eden: "עדן", efrat: "אפרת", einat: "עינת", elad: "אלעד",
  eleanor: "אלינור", eli: "אלי", eliana: "אליאנה", eliezer: "אליעזר",
  elijah: "אליהו", eliran: "אלירן", elisheva: "אלישבע", ella: "אלה",
  elon: "אלון", emily: "אמילי", emma: "אמה", esther: "אסתר",
  ethan: "איתן", eyal: "אייל", ezra: "עזרא",
  gal: "גל", galit: "גלית", gili: "גילי", gil: "גיל",
  golan: "גולן", guy: "גיא",
  hadas: "הדס", hannah: "חנה", hila: "הילה", hili: "הילי",
  ilan: "אילן", irit: "ירית", isaac: "יצחק", israel: "ישראל",
  itai: "איתי", itay: "איתי",
  jacob: "יעקב", james: "ג'יימס", jason: "ג'ייסון", jessica: "ג'סיקה",
  john: "ג'ון", jonathan: "יונתן", joseph: "יוסף", joshua: "יהושע",
  julia: "יוליה", juliet: "ג'ולייט",
  karen: "קארן", keren: "קרן",
  lavi: "לביא", leah: "לאה", levi: "לוי", liat: "ליאת",
  lior: "ליאור", liora: "ליאורה", lisa: "ליסה",
  matan: "מתן", maya: "מאיה", meir: "מאיר", menachem: "מנחם",
  michal: "מיכל", michael: "מיכאל", mike: "מייק", miriam: "מרים",
  mor: "מור", mordechai: "מרדכי", moshe: "משה", moses: "משה",
  naomi: "נעמי", natan: "נתן", nathaniel: "נתנאל", noa: "נועה",
  noam: "נועם", noga: "נגה",
  ofir: "אופיר", omer: "עומר", oren: "אורן", orit: "אורית",
  orly: "אורלי", or: "אור",
  rachel: "רחל", ran: "רן", raz: "רז", rebecca: "רבקה",
  reut: "רעות", rivka: "רבקה", robert: "רוברט", roi: "רועי",
  ron: "רון", roni: "רוני", ruth: "רות",
  samuel: "שמואל", sarah: "שרה", sara: "שרה", sharon: "שרון",
  shira: "שירה", shimon: "שמעון", shlomo: "שלמה", simon: "שמעון",
  solomon: "שלמה",
  tal: "טל", tali: "טלי", tamar: "תמר", tomer: "תומר", tzvi: "צבי",
  uri: "אורי",
  william: "ויליאם",
  yael: "יעל", yair: "יאיר", yaniv: "יניב", yarden: "ירדן",
  yaron: "ירון", yitzhak: "יצחק", yoav: "יואב", yonatan: "יונתן",
  yoni: "יוני",
  ziv: "זיו", zohar: "זוהר",
};

export function lookupHebrew(firstName: string): string | null {
  if (!firstName) return null;
  return NAME_LOOKUP[firstName.toLowerCase()] ?? null;
}
