const NAME_LOOKUP: Record<string, string> = {
  aaron: "אהרון", abel: "הבל", abigail: "אביגיל", abraham: "אברהם",
  adam: "אדם", adina: "אדינה", alon: "אלון", amir: "אמיר",
  amit: "עמית", anat: "ענת", ari: "ארי", ariel: "אריאל",
  asher: "אשר", avi: "אבי", avigail: "אביגיל", avital: "אביטל",
  avraham: "אברהם",
  bar: "בר", barak: "ברק", baruch: "ברוך", bat: "בת", batya: "בתיה",
  becca: "רבקה", benny: "בני", benjamin: "בנימין", ben: "בן",
  caleb: "כלב", carmel: "כרמל", carmi: "כרמי",
  dan: "דן", dana: "דנה", daniel: "דניאל", dani: "דני", dotan: "דותן",
  daphna: "דפנה", david: "דוד", debbie: "דבורה", deborah: "דבורה",
  devorah: "דבורה", dina: "דינה", dorin: "דורין", dorit: "דורית", doron: "דורון",
  adi: "עדי", eden: "עדן", efrat: "אפרת", einat: "עינת", einav: "עינב", elad: "אלעד",
  eleanor: "אלינור", elinor: "אלינור", eli: "אלי", eliana: "אליאנה", eliezer: "אליעזר",
  elijah: "אליהו", eliran: "אלירן", elisheva: "אלישבע", ella: "אלה",
  elon: "אלון", emily: "אמילי", emma: "אמה", eran: "ערן", esther: "אסתר",
  ethan: "איתן", eyal: "אייל", ezra: "עזרא",
  gal: "גל", galit: "גלית", gideon: "גדעון", gili: "גילי", gil: "גיל",
  golan: "גולן", guy: "גיא",
  hadar: "הדר", hadas: "הדס", hagai: "חגי", hanan: "חנן", hannah: "חנה", hila: "הילה", hili: "הילי",
  ido: "עידו", igal: "יגאל", ilan: "אילן", inbar: "ענבר", irit: "ירית",
  isaac: "יצחק", israel: "ישראל", itai: "איתי", itay: "איתי",
  jacob: "יעקב", james: "ג'יימס", jason: "ג'ייסון", jessica: "ג'סיקה",
  john: "ג'ון", jonathan: "יונתן", joseph: "יוסף", joshua: "יהושע",
  julia: "יוליה", juliet: "ג'ולייט",
  karen: "קארן", keren: "קרן",
  lavi: "לביא", leah: "לאה", levi: "לוי", liat: "ליאת",
  lior: "ליאור", liora: "ליאורה", liron: "לירון", lisa: "ליסה",
  maayan: "מעיין", matan: "מתן", maya: "מאיה", meir: "מאיר", menachem: "מנחם", meital: "מיטל",
  michal: "מיכל", michael: "מיכאל", mike: "מייק", miriam: "מרים",
  mor: "מור", mordechai: "מרדכי", moshe: "משה", moses: "משה",
  nadav: "נדב", naomi: "נעמי", natan: "נתן", nathaniel: "נתנאל", netanel: "נתנאל",
  nevo: "נבו", nili: "נילי", nir: "ניר", noa: "נועה", noam: "נועם", noga: "נגה", nurit: "נורית",
  oded: "עודד", ofir: "אופיר", ofra: "עופרה", ohad: "אוהד",
  omri: "עמרי", omer: "עומר", oren: "אורן", orit: "אורית",
  orly: "אורלי", or: "אור",
  rachel: "רחל", rafi: "רפי", ran: "רן", raz: "רז", rebecca: "רבקה",
  reut: "רעות", reuven: "ראובן", rivka: "רבקה", robert: "רוברט", roi: "רועי",
  ron: "רון", ronen: "רונן", roni: "רוני", ruth: "רות",
  saar: "סער", sagi: "שגיא", sam: "סם", samuel: "שמואל", sapir: "ספיר", sarah: "שרה", sara: "שרה", sivan: "סיוון",
  shani: "שני", sharon: "שרון", shay: "שי", shira: "שירה", shimon: "שמעון",
  shlomo: "שלמה", sigal: "שגל", simon: "שמעון", smadar: "סמדר", solomon: "שלמה",
  tal: "טל", tali: "טלי", tamar: "תמר", tamir: "תמיר", tomer: "תומר", tzachi: "צחי", tzvi: "צבי",
  uri: "אורי", uzi: "עוזי",
  william: "ויליאם",
  yael: "יעל", yair: "יאיר", yaniv: "יניב", yarden: "ירדן",
  yaron: "ירון", yehuda: "יהודה", yishai: "ישי", yitzhak: "יצחק",
  yoav: "יואב", yonatan: "יונתן", yoni: "יוני", yuval: "יובל",
  ziv: "זיו", zohar: "זוהר",
};

export function lookupHebrew(firstName: string): string | null {
  if (!firstName) return null;
  return NAME_LOOKUP[firstName.toLowerCase()] ?? null;
}
