// Regenerates lib/prospecting/industries.ts from LinkedIn's official Industry Codes V2
// reference table. These numeric IDs are exactly what the people-search
// industry=["..."] URL facet accepts (verified against the live search UI).
// Run from repo root: npx tsx scripts/generate-linkedin-industries.ts
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE_URL =
  "https://learn.microsoft.com/en-us/linkedin/shared/references/reference-tables/industry-codes-v2";

function stripTags(html: string): string {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&gt;/g, ">")
    .replace(/&lt;/g, "<")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
  const html = await res.text();

  const rows = html.match(/<tr>[\s\S]*?<\/tr>/g) ?? [];
  const byId = new Map<string, { id: string; label: string; path: string }>();
  for (const row of rows) {
    const cells = [...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((m) => stripTags(m[1]));
    // Data rows: [id, name, hierarchy, description]. Header/legacy-mapping rows don't match.
    if (cells.length < 3 || !/^\d+$/.test(cells[0])) continue;
    const [id, label, path] = cells;
    if (!byId.has(id)) byId.set(id, { id, label, path });
  }

  const industries = [...byId.values()].sort((a, b) => a.label.localeCompare(b.label));
  if (industries.length < 400) {
    throw new Error(`suspiciously few industries parsed: ${industries.length} — page layout may have changed`);
  }

  const out = `// AUTO-GENERATED by scripts/generate-linkedin-industries.ts — do not edit by hand.
// Source: LinkedIn Industry Codes V2 (${SOURCE_URL})
// These numeric IDs are what LinkedIn's people-search industry=["..."] facet accepts.
export type LinkedInIndustry = { id: string; label: string; path: string };

export const LINKEDIN_INDUSTRIES: LinkedInIndustry[] = ${JSON.stringify(industries, null, 2)};

export const INDUSTRY_BY_ID: ReadonlyMap<string, LinkedInIndustry> = new Map(
  LINKEDIN_INDUSTRIES.map((i) => [i.id, i])
);
`;
  writeFileSync(resolve(process.cwd(), "lib/prospecting/industries.ts"), out);
  console.log(`wrote ${industries.length} industries to lib/prospecting/industries.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
