// AUTO-GENERATED by scripts/generate-linkedin-industries.ts — do not edit by hand.
// Source: LinkedIn Industry Codes V2 (https://learn.microsoft.com/en-us/linkedin/shared/references/reference-tables/industry-codes-v2)
// These numeric IDs are what LinkedIn's people-search industry=["..."] facet accepts.
export type LinkedInIndustry = { id: string; label: string; path: string };

export const LINKEDIN_INDUSTRIES: LinkedInIndustry[] = [
  {
    "id": "799",
    "label": "Abrasives and Nonmetallic Minerals Manufacturing",
    "path": "Manufacturing > Glass, Ceramics and Concrete Manufacturing > Abrasives and Nonmetallic Minerals Manufacturing"
  },
  {
    "id": "3246",
    "label": "Accessible Architecture and Design",
    "path": "Professional Services > Architecture and Planning > Accessible Architecture and Design"
  },
  {
    "id": "3245",
    "label": "Accessible Hardware Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Computer Hardware Manufacturing > Accessible Hardware Manufacturing"
  },
  {
    "id": "2190",
    "label": "Accommodation Services",
    "path": "Accommodation Services"
  },
  {
    "id": "47",
    "label": "Accounting",
    "path": "Professional Services > Accounting"
  },
  {
    "id": "73",
    "label": "Administration of Justice",
    "path": "Government Administration > Administration of Justice"
  },
  {
    "id": "1912",
    "label": "Administrative and Support Services",
    "path": "Administrative and Support Services"
  },
  {
    "id": "80",
    "label": "Advertising Services",
    "path": "Professional Services > Advertising Services"
  },
  {
    "id": "709",
    "label": "Agricultural Chemical Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Agricultural Chemical Manufacturing"
  },
  {
    "id": "901",
    "label": "Agriculture, Construction, Mining Machinery Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Agriculture, Construction, Mining Machinery Manufacturing"
  },
  {
    "id": "2366",
    "label": "Air, Water, and Waste Program Management",
    "path": "Government Administration > Environmental Quality Programs > Air, Water, and Waste Program Management"
  },
  {
    "id": "94",
    "label": "Airlines and Aviation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Airlines and Aviation"
  },
  {
    "id": "120",
    "label": "Alternative Dispute Resolution",
    "path": "Professional Services > Legal Services > Alternative Dispute Resolution"
  },
  {
    "id": "3253",
    "label": "Alternative Fuel Vehicle Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Motor Vehicle Manufacturing > Alternative Fuel Vehicle Manufacturing"
  },
  {
    "id": "125",
    "label": "Alternative Medicine",
    "path": "Hospitals and Health Care > Medical Practices > Alternative Medicine"
  },
  {
    "id": "2077",
    "label": "Ambulance Services",
    "path": "Hospitals and Health Care > Medical Practices > Ambulance Services"
  },
  {
    "id": "2167",
    "label": "Amusement Parks and Arcades",
    "path": "Entertainment Providers > Recreational Facilities > Amusement Parks and Arcades"
  },
  {
    "id": "481",
    "label": "Animal Feed Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Animal Feed Manufacturing"
  },
  {
    "id": "3215",
    "label": "Animation",
    "path": "This industry includes entities that produce and/or sell art made with a method in which figures are manipulated to appear as moving images."
  },
  {
    "id": "127",
    "label": "Animation and Post-production",
    "path": "Technology, Information and Media > Media and Telecommunications > Movies, Videos and Sound > Animation and Post-production"
  },
  {
    "id": "3190",
    "label": "Apparel and Fashion",
    "path": "This industry includes entities that design, manufacture, and distribute clothing and apparel."
  },
  {
    "id": "598",
    "label": "Apparel Manufacturing",
    "path": "Manufacturing > Apparel Manufacturing"
  },
  {
    "id": "112",
    "label": "Appliances, Electrical, and Electronics Manufacturing",
    "path": "Manufacturing > Appliances, Electrical, and Electronics Manufacturing"
  },
  {
    "id": "852",
    "label": "Architectural and Structural Metal Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Architectural and Structural Metal Manufacturing"
  },
  {
    "id": "50",
    "label": "Architecture and Planning",
    "path": "Professional Services > Architecture and Planning"
  },
  {
    "id": "71",
    "label": "Armed Forces",
    "path": "Government Administration > Military and International Affairs > Armed Forces"
  },
  {
    "id": "703",
    "label": "Artificial Rubber and Synthetic Fiber Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Artificial Rubber and Synthetic Fiber Manufacturing"
  },
  {
    "id": "38",
    "label": "Artists and Writers",
    "path": "Entertainment Providers > Artists and Writers"
  },
  {
    "id": "3204",
    "label": "Arts and Crafts",
    "path": "This industry includes entities that participate in economic activities related to the creation of goods by artisans or skilled craftspeople or the design, development, manufacturing, and distribution of craft supplies."
  },
  {
    "id": "973",
    "label": "Audio and Video Equipment Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Audio and Video Equipment Manufacturing"
  },
  {
    "id": "147",
    "label": "Automation Machinery Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Automation Machinery Manufacturing"
  },
  {
    "id": "3198",
    "label": "Automotive",
    "path": "This industry includes entities that participate in the design, development, manufacturing, marketing, and selling of motor vehicles."
  },
  {
    "id": "3226",
    "label": "Aviation & Aerospace",
    "path": "This industry includes entities that engage in the research, development, manufacture and sale of flight vehicles, major flight-vehicle subsystems such as propulsion and avionics and key support systems necessary for the testing, operation, and maintenance of flight vehicles."
  },
  {
    "id": "52",
    "label": "Aviation and Aerospace Component Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Aviation and Aerospace Component Manufacturing"
  },
  {
    "id": "529",
    "label": "Baked Goods Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Baked Goods Manufacturing"
  },
  {
    "id": "41",
    "label": "Banking",
    "path": "Financial Services > Credit Intermediation > Banking"
  },
  {
    "id": "2217",
    "label": "Bars, Taverns, and Nightclubs",
    "path": "Accommodation Services > Food and Beverage Services > Bars, Taverns, and Nightclubs"
  },
  {
    "id": "2197",
    "label": "Bed-and-Breakfasts, Hostels, Homestays",
    "path": "Accommodation Services > Hospitality > Bed-and-Breakfasts, Hostels, Homestays"
  },
  {
    "id": "142",
    "label": "Beverage Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Beverage Manufacturing"
  },
  {
    "id": "390",
    "label": "Biomass Electric Power Generation",
    "path": "Utilities > Electric Power Generation > Renewable Energy Power Generation > Biomass Electric Power Generation"
  },
  {
    "id": "3238",
    "label": "Biotechnology",
    "path": "This industry includes entities that use living organisms and molecular biology to produce healthcare-related products."
  },
  {
    "id": "12",
    "label": "Biotechnology Research",
    "path": "Professional Services > Research Services > Biotechnology Research"
  },
  {
    "id": "3134",
    "label": "Blockchain Services",
    "path": "Technology, Information and Media > Technology, Information and Internet > Data Infrastructure and Analytics > Blockchain Services"
  },
  {
    "id": "3125",
    "label": "Blogs",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services >Internet Publishing > Blogs"
  },
  {
    "id": "861",
    "label": "Boilers, Tanks, and Shipping Container Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Boilers, Tanks, and Shipping Container Manufacturing"
  },
  {
    "id": "82",
    "label": "Book and Periodical Publishing",
    "path": "Technology, Information and Media > Media and Telecommunications > Book and Periodical Publishing"
  },
  {
    "id": "1602",
    "label": "Book Publishing",
    "path": "Technology, Information and Media > Media and Telecommunications > Book and Periodical Publishing > Book Publishing"
  },
  {
    "id": "562",
    "label": "Breweries",
    "path": "Manufacturing > Food and Beverage Manufacturing > > Breweries"
  },
  {
    "id": "36",
    "label": "Broadcast Media Production and Distribution",
    "path": "Technology, Information and Media > Media and Telecommunications > Broadcast Media Production and Distribution"
  },
  {
    "id": "406",
    "label": "Building Construction",
    "path": "Construction > Building Construction"
  },
  {
    "id": "453",
    "label": "Building Equipment Contractors",
    "path": "Construction > Specialty Trade Contractors > Building Equipment Contractors"
  },
  {
    "id": "460",
    "label": "Building Finishing Contractors",
    "path": "Construction > Specialty Trade Contractors > Building Finishing Contractors"
  },
  {
    "id": "3197",
    "label": "Building Materials",
    "path": "This industry includes entities that produce and/or sell building materials, such as lumber, plywood, millwork, and wood panels; brick, stone, and related construction materials; roofing, siding, and insulation materials; and other construction materials, including manufactured homes (such as mobile homes) and/or prefabricated buildings."
  },
  {
    "id": "436",
    "label": "Building Structure and Exterior Contractors",
    "path": "Construction > Specialty Trade Contractors > Building Structure and Exterior Contractors"
  },
  {
    "id": "11",
    "label": "Business Consulting and Services",
    "path": "Professional Services > Business Consulting and Services"
  },
  {
    "id": "3129",
    "label": "Business Content",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services > Internet Publishing > Business Content"
  },
  {
    "id": "3128",
    "label": "Business Intelligence Platforms",
    "path": "Technology, Information and Media > Technology, Information and Internet > Data Infrastructure and Analytics > Business Intelligence Platforms"
  },
  {
    "id": "3211",
    "label": "Business Supplies and Equipment",
    "path": "This industry includes entities that produce and/or sell consumables and equipment regularly used in offices by businesses and other organizations."
  },
  {
    "id": "1641",
    "label": "Cable and Satellite Programming",
    "path": "Technology, Information and Media > Media and Telecommunications > Broadcast Media Production and Distribution > Cable and Satellite Programming"
  },
  {
    "id": "129",
    "label": "Capital Markets",
    "path": "Financial Services > Capital Markets"
  },
  {
    "id": "2212",
    "label": "Caterers",
    "path": "Accommodation Services > Food and Beverage Services > Caterers"
  },
  {
    "id": "54",
    "label": "Chemical Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing"
  },
  {
    "id": "690",
    "label": "Chemical Raw Materials Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Chemical Raw Materials Manufacturing"
  },
  {
    "id": "2128",
    "label": "Child Day Care Services",
    "path": "Hospitals and Health Care > Individual and Family Services > Child Day Care Services"
  },
  {
    "id": "2048",
    "label": "Chiropractors",
    "path": "Hospitals and Health Care > Medical Practices > Chiropractors"
  },
  {
    "id": "2139",
    "label": "Circuses and Magic Shows",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Circuses and Magic Shows"
  },
  {
    "id": "90",
    "label": "Civic and Social Organizations",
    "path": "Consumer Services > Civic and Social Organizations"
  },
  {
    "id": "51",
    "label": "Civil Engineering",
    "path": "Construction > Civil Engineering"
  },
  {
    "id": "1738",
    "label": "Claims Adjusting, Actuarial Services",
    "path": "Financial Services > Insurance > Claims Adjusting, Actuarial Services"
  },
  {
    "id": "773",
    "label": "Clay and Refractory Products Manufacturing",
    "path": "Manufacturing > Glass, Ceramics and Concrete Manufacturing > Clay and Refractory Products Manufacturing"
  },
  {
    "id": "3252",
    "label": "Climate Data and Analytics",
    "path": "Technology, Information and Media > Technology, Information and Internet > Data Infrastructure and Analytics > Climate Data and Analytics"
  },
  {
    "id": "3251",
    "label": "Climate Technology Product Manufacturing",
    "path": "Manufacturing > Climate Technology Products Manufacturing"
  },
  {
    "id": "341",
    "label": "Coal Mining",
    "path": "Oil, Gas, and Mining > Mining > Coal Mining"
  },
  {
    "id": "1938",
    "label": "Collection Agencies",
    "path": "Administrative and Support Services > Collection Agencies"
  },
  {
    "id": "1798",
    "label": "Commercial and Industrial Equipment Rental",
    "path": "Real Estate and Equipment Rental Services > Equipment Rental Services > Commercial and Industrial Equipment Rental"
  },
  {
    "id": "2247",
    "label": "Commercial and Industrial Machinery Maintenance",
    "path": "Consumer Services > Repair and Maintenance > Commercial and Industrial Machinery Maintenance"
  },
  {
    "id": "918",
    "label": "Commercial and Service Industry Machinery Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Commercial and Service Industry Machinery Manufacturing"
  },
  {
    "id": "3219",
    "label": "Commercial Real Estate",
    "path": "This industry includes entities that manage, construct, design, or sell real estate (buildings or land) intended to generate a profit, either from capital gains or rental income."
  },
  {
    "id": "964",
    "label": "Communications Equipment Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Communications Equipment Manufacturing"
  },
  {
    "id": "2374",
    "label": "Community Development and Urban Planning",
    "path": "Government Administration > Housing and Community Development > Community Development and Urban Planning"
  },
  {
    "id": "2115",
    "label": "Community Services",
    "path": "Hospitals and Health Care > Community Services"
  },
  {
    "id": "118",
    "label": "Computer and Network Security",
    "path": "Professional Services > IT Services and IT Consulting > Computer and Network Security"
  },
  {
    "id": "109",
    "label": "Computer Games",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Computer Games"
  },
  {
    "id": "3235",
    "label": "Computer Hardware",
    "path": "This industry includes entities that produce and/or sell the physical parts of a computer, such as the case, central processing unit (CPU), random access memory (RAM), monitor, mouse, keyboard, computer data storage, graphics card, sound card, speakers and motherboard."
  },
  {
    "id": "3",
    "label": "Computer Hardware Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Computer Hardware Manufacturing"
  },
  {
    "id": "3234",
    "label": "Computer Networking",
    "path": "This industry includes entities that produce, sell, and/or provide services for interconnected computing devices that can exchange data and share resources with each other."
  },
  {
    "id": "5",
    "label": "Computer Networking Products",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Computer Networking Products"
  },
  {
    "id": "24",
    "label": "Computers and Electronics Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing"
  },
  {
    "id": "2368",
    "label": "Conservation Programs",
    "path": "Government Administration > Environmental Quality Programs > Conservation Programs"
  },
  {
    "id": "48",
    "label": "Construction",
    "path": "Construction"
  },
  {
    "id": "871",
    "label": "Construction Hardware Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Construction Hardware Manufacturing"
  },
  {
    "id": "3191",
    "label": "Consumer Electronics",
    "path": "This industry includes entities that produce and/or sell electronic equipment intended for everyday use."
  },
  {
    "id": "3192",
    "label": "Consumer Goods",
    "path": "This industry includes entities that produce and/or sell final products ready for use by the consumer."
  },
  {
    "id": "1786",
    "label": "Consumer Goods Rental",
    "path": "Real Estate and Equipment Rental Services > Equipment Rental Services > Consumer Goods Rental"
  },
  {
    "id": "91",
    "label": "Consumer Services",
    "path": "Consumer Services"
  },
  {
    "id": "3068",
    "label": "Correctional Institutions",
    "path": "Government Administration > Administration of Justice > Correctional Institutions"
  },
  {
    "id": "3189",
    "label": "Cosmetics",
    "path": "This industry includes entities that manufacture and distribute cosmetic products, such as foundation, mascara, skincare, haircare and soap."
  },
  {
    "id": "2019",
    "label": "Cosmetology and Barber Schools",
    "path": "Education > Technical and Vocational Training > Cosmetology and Barber Schools"
  },
  {
    "id": "3065",
    "label": "Courts of Law",
    "path": "Government Administration > Administration of Justice > Courts of Law"
  },
  {
    "id": "1673",
    "label": "Credit Intermediation",
    "path": "Financial Services > Credit Intermediation"
  },
  {
    "id": "849",
    "label": "Cutlery and Handtool Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Cutlery and Handtool Manufacturing"
  },
  {
    "id": "3199",
    "label": "Dairy",
    "path": "This industry includes entities that produce and/or sell dairy products made from raw milk, processed milk, and dairy substitutes."
  },
  {
    "id": "65",
    "label": "Dairy Product Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Dairy Product Manufacturing"
  },
  {
    "id": "2135",
    "label": "Dance Companies",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Dance Companies"
  },
  {
    "id": "2458",
    "label": "Data Infrastructure and Analytics",
    "path": "Technology, Information and Media > Technology, Information and Internet > Data Infrastructure and Analytics"
  },
  {
    "id": "3130",
    "label": "Data Security Software Products",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Data Security Software Products"
  },
  {
    "id": "3187",
    "label": "Defense & Space",
    "path": "This industry includes entities that produce and/or sell guided missiles and space vehicles."
  },
  {
    "id": "1",
    "label": "Defense and Space Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Defense and Space Manufacturing"
  },
  {
    "id": "2045",
    "label": "Dentists",
    "path": "Hospitals and Health Care > Medical Practices > Dentists"
  },
  {
    "id": "3227",
    "label": "Design",
    "path": "This industry includes entities that create plans or specifications for the production of an object or system, or for the implementation of an activity or process or the result of that plan or specification in the form of a prototype, product, or process."
  },
  {
    "id": "99",
    "label": "Design Services",
    "path": "Professional Services > Design Services"
  },
  {
    "id": "3101",
    "label": "Desktop Computing Software Products",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Desktop Computing Software Products"
  },
  {
    "id": "3244",
    "label": "Digital Accessibility Services",
    "path": "Professional Services > IT Services and IT Consulting > Digital Accessibility Services"
  },
  {
    "id": "564",
    "label": "Distilleries",
    "path": "Manufacturing > Food and Beverage Manufacturing > > Distilleries"
  },
  {
    "id": "3208",
    "label": "E-Learning",
    "path": "This industry includes entities that use a combination of computer hardware, software, and educational theory and practice to facilitate learning."
  },
  {
    "id": "132",
    "label": "E-Learning Providers",
    "path": "Education > E-Learning Providers"
  },
  {
    "id": "2375",
    "label": "Economic Programs",
    "path": "Government Administration > Economic Programs"
  },
  {
    "id": "1999",
    "label": "Education",
    "path": "Education"
  },
  {
    "id": "69",
    "label": "Education Administration Programs",
    "path": "Government Administration > Health and Human Services > Education Administration Programs"
  },
  {
    "id": "3200",
    "label": "Education Management",
    "path": "This industry includes entities that participate in activities related to educational leadership and management."
  },
  {
    "id": "998",
    "label": "Electric Lighting Equipment Manufacturing",
    "path": "Manufacturing > Appliances, Electrical, and Electronics Manufacturing > Electric Lighting Equipment Manufacturing"
  },
  {
    "id": "383",
    "label": "Electric Power Generation",
    "path": "Utilities > Electric Power Generation"
  },
  {
    "id": "382",
    "label": "Electric Power Transmission, Control, and Distribution",
    "path": "Utilities > Electric Power Transmission, Control, and Distribution"
  },
  {
    "id": "2468",
    "label": "Electrical Equipment Manufacturing",
    "path": "Manufacturing > Appliances, Electrical, and Electronics Manufacturing > Electrical Equipment Manufacturing"
  },
  {
    "id": "2240",
    "label": "Electronic and Precision Equipment Maintenance",
    "path": "Consumer Services > Repair and Maintenance > Electronic and Precision Equipment Maintenance"
  },
  {
    "id": "3099",
    "label": "Embedded Software Products",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Embedded Software Products"
  },
  {
    "id": "2122",
    "label": "Emergency and Relief Services",
    "path": "Hospitals and Health Care > Individual and Family Services > Emergency and Relief Services"
  },
  {
    "id": "3242",
    "label": "Engineering Services",
    "path": "Professional Services > Engineering Services"
  },
  {
    "id": "935",
    "label": "Engines and Power Transmission Equipment Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Engines and Power Transmission Equipment Manufacturing"
  },
  {
    "id": "3237",
    "label": "Entertainment",
    "path": "This industry includes entities that are involved in the production and distribution of mass media entertainment."
  },
  {
    "id": "28",
    "label": "Entertainment Providers",
    "path": "Entertainment Providers"
  },
  {
    "id": "388",
    "label": "Environmental Quality Programs",
    "path": "Government Administration > Environmental Quality Programs"
  },
  {
    "id": "86",
    "label": "Environmental Services",
    "path": "Professional Services > Business Consulting and Services > Environmental Services"
  },
  {
    "id": "1779",
    "label": "Equipment Rental Services",
    "path": "Real Estate and Equipment Rental Services > Equipment Rental Services"
  },
  {
    "id": "110",
    "label": "Events Services",
    "path": "Administrative and Support Services > Events Services"
  },
  {
    "id": "76",
    "label": "Executive Offices",
    "path": "Government Administration > Public Policy Offices > Executive Offices"
  },
  {
    "id": "1923",
    "label": "Executive Search Services",
    "path": "Administrative and Support Services > Staffing and Recruiting > Executive Search Services"
  },
  {
    "id": "840",
    "label": "Fabricated Metal Products",
    "path": "Manufacturing > Fabricated Metal Products"
  },
  {
    "id": "122",
    "label": "Facilities Services",
    "path": "Administrative and Support Services > Facilities Services"
  },
  {
    "id": "2060",
    "label": "Family Planning Centers",
    "path": "Hospitals and Health Care > Medical Practices > Family Planning Centers"
  },
  {
    "id": "63",
    "label": "Farming",
    "path": "Farming, Ranching, Forestry > Farming"
  },
  {
    "id": "201",
    "label": "Farming, Ranching, Forestry",
    "path": "Farming, Ranching, Forestry"
  },
  {
    "id": "615",
    "label": "Fashion Accessories Manufacturing",
    "path": "Manufacturing > Apparel Manufacturing > Fashion Accessories Manufacturing"
  },
  {
    "id": "43",
    "label": "Financial Services",
    "path": "Financial Services"
  },
  {
    "id": "3196",
    "label": "Fine Art",
    "path": "This industry includes entities that produce and/or sell products related to the visual arts such as painting, drawing, printmaking, sculpture, ceramics, and photography."
  },
  {
    "id": "2025",
    "label": "Fine Arts Schools",
    "path": "Education > Technical and Vocational Training > Fine Arts Schools"
  },
  {
    "id": "3070",
    "label": "Fire Protection",
    "path": "Government Administration > Administration of Justice > Fire Protection"
  },
  {
    "id": "66",
    "label": "Fisheries",
    "path": "Farming, Ranching, Forestry > Ranching and Fisheries > Fisheries"
  },
  {
    "id": "2020",
    "label": "Flight Training",
    "path": "Education > Technical and Vocational Training > Flight Training"
  },
  {
    "id": "3195",
    "label": "Food & Beverages",
    "path": "This industry includes entities that prepare, present and serve food and beverages to customers."
  },
  {
    "id": "23",
    "label": "Food and Beverage Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing"
  },
  {
    "id": "1339",
    "label": "Food and Beverage Retail",
    "path": "Retail > Food and Beverage Retail"
  },
  {
    "id": "34",
    "label": "Food and Beverage Services",
    "path": "Accommodation Services > Food and Beverage Services"
  },
  {
    "id": "3224",
    "label": "Food Production",
    "path": "This industry includes entities that transform livestock and agricultural products into products for intermediate or final consumption."
  },
  {
    "id": "2255",
    "label": "Footwear and Leather Goods Repair",
    "path": "Consumer Services > Repair and Maintenance > Footwear and Leather Goods Repair"
  },
  {
    "id": "622",
    "label": "Footwear Manufacturing",
    "path": "Manufacturing > Leather Product Manufacturing > Footwear Manufacturing"
  },
  {
    "id": "298",
    "label": "Forestry and Logging",
    "path": "Farming, Ranching, Forestry > Forestry and Logging"
  },
  {
    "id": "385",
    "label": "Fossil Fuel Electric Power Generation",
    "path": "Utilities > Electric Power Generation > Fossil Fuel Electric Power Generation"
  },
  {
    "id": "87",
    "label": "Freight and Package Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Freight and Package Transportation"
  },
  {
    "id": "504",
    "label": "Fruit and Vegetable Preserves Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Fruit and Vegetable Preserves Manufacturing"
  },
  {
    "id": "3255",
    "label": "Fuel Cell Manufacturing",
    "path": "Manufacturing > Appliances, Electrical, and Electronics Manufacturing > Electrical Equipment Manufacturing > Fuel Cell Manufacturing"
  },
  {
    "id": "101",
    "label": "Fundraising",
    "path": "Administrative and Support Services > Fundraising"
  },
  {
    "id": "1742",
    "label": "Funds and Trusts",
    "path": "Financial Services > Funds and Trusts"
  },
  {
    "id": "3193",
    "label": "Furniture",
    "path": "This industry includes entities that participate in the design, manufacture, distribution, and sale of household furniture (such as baby furniture, box springs, and mattresses) and outdoor furniture; office furniture (except those sold in combination with office supplies and equipment), and other furniture objects."
  },
  {
    "id": "26",
    "label": "Furniture and Home Furnishings Manufacturing",
    "path": "Manufacturing > Furniture and Home Furnishings Manufacturing"
  },
  {
    "id": "29",
    "label": "Gambling Facilities and Casinos",
    "path": "Entertainment Providers > Recreational Facilities > Gambling Facilities and Casinos"
  },
  {
    "id": "389",
    "label": "Geothermal Electric Power Generation",
    "path": "Utilities > Electric Power Generation > Renewable Energy Power Generation > Geothermal Electric Power Generation"
  },
  {
    "id": "779",
    "label": "Glass Product Manufacturing",
    "path": "Manufacturing > Glass, Ceramics and Concrete Manufacturing > Glass Product Manufacturing"
  },
  {
    "id": "145",
    "label": "Glass, Ceramics and Concrete Manufacturing",
    "path": "Manufacturing > Glass, Ceramics and Concrete Manufacturing"
  },
  {
    "id": "2179",
    "label": "Golf Courses and Country Clubs",
    "path": "Entertainment Providers > Recreational Facilities > Golf Courses and Country Clubs"
  },
  {
    "id": "75",
    "label": "Government Administration",
    "path": "Government Administration"
  },
  {
    "id": "3232",
    "label": "Government Relations",
    "path": "This industry includes entities that monitor and engage in the federal and state legislative process, facilitate relationships with members of local, state, and federal administrative agencies, departments, commissions, and boards; and engage in grassroots lobbying and legislative policy strategies."
  },
  {
    "id": "148",
    "label": "Government Relations Services",
    "path": "Professional Services > Advertising Services > Government Relations Services"
  },
  {
    "id": "140",
    "label": "Graphic Design",
    "path": "Professional Services > Design Services > Graphic Design"
  },
  {
    "id": "1495",
    "label": "Ground Passenger Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation"
  },
  {
    "id": "2353",
    "label": "Health and Human Services",
    "path": "Government Administration > Health and Human Services"
  },
  {
    "id": "3207",
    "label": "Health, Wellness and Fitness",
    "path": "This industry includes entities that produce and deliver products and services that promote physical and mental wellbeing."
  },
  {
    "id": "68",
    "label": "Higher Education",
    "path": "Education > Higher Education"
  },
  {
    "id": "431",
    "label": "Highway, Street, and Bridge Construction",
    "path": "Construction > Civil Engineering > Highway, Street, and Bridge Construction"
  },
  {
    "id": "2161",
    "label": "Historical Sites",
    "path": "Entertainment Providers > Museums, Historical Sites, and Zoos > Historical Sites"
  },
  {
    "id": "1905",
    "label": "Holding Companies",
    "path": "Holding Companies"
  },
  {
    "id": "2074",
    "label": "Home Health Care Services",
    "path": "Hospitals and Health Care > Medical Practices > Home Health Care Services"
  },
  {
    "id": "150",
    "label": "Horticulture",
    "path": "Farming, Ranching, Forestry > Farming > Horticulture"
  },
  {
    "id": "31",
    "label": "Hospitality",
    "path": "Accommodation Services > Hospitality"
  },
  {
    "id": "2081",
    "label": "Hospitals",
    "path": "Hospitals and Health Care > Hospitals"
  },
  {
    "id": "14",
    "label": "Hospitals and Health Care",
    "path": "Hospitals and Health Care"
  },
  {
    "id": "2194",
    "label": "Hotels and Motels",
    "path": "Accommodation Services > Hospitality > Hotels and Motels"
  },
  {
    "id": "1080",
    "label": "Household and Institutional Furniture Manufacturing",
    "path": "Manufacturing > Furniture and Home Furnishings Manufacturing > Household and Institutional Furniture Manufacturing"
  },
  {
    "id": "1005",
    "label": "Household Appliance Manufacturing",
    "path": "Manufacturing > Appliances, Electrical, and Electronics Manufacturing > Household Appliance Manufacturing"
  },
  {
    "id": "2318",
    "label": "Household Services",
    "path": "Consumer Services > Household Services"
  },
  {
    "id": "2369",
    "label": "Housing and Community Development",
    "path": "Government Administration > Housing and Community Development"
  },
  {
    "id": "3081",
    "label": "Housing Programs",
    "path": "Government Administration > Housing and Community Development > Housing Programs"
  },
  {
    "id": "3210",
    "label": "Human Resources",
    "path": "This industry includes entities that are involved in finding, screening, recruiting, and training job applicants, as well as administering benefits"
  },
  {
    "id": "137",
    "label": "Human Resources Services",
    "path": "Professional Services > Business Consulting and Services > Human Resources Services"
  },
  {
    "id": "923",
    "label": "HVAC and Refrigeration Equipment Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > HVAC and Refrigeration Equipment Manufacturing"
  },
  {
    "id": "384",
    "label": "Hydroelectric Power Generation",
    "path": "Utilities > Electric Power Generation > Renewable Energy Power Generation > Hydroelectric Power Generation"
  },
  {
    "id": "3209",
    "label": "Import and Export",
    "path": "This industry includes entities that participate in international trade and exchange of goods, products and services."
  },
  {
    "id": "88",
    "label": "Individual and Family Services",
    "path": "Hospitals and Health Care > Individual and Family Services"
  },
  {
    "id": "3216",
    "label": "Industrial Automation",
    "path": "This industry includes entities that produce and/or sell autonomous control systems that use technologies such as robotics and computer software to handle processes and machinery."
  },
  {
    "id": "135",
    "label": "Industrial Machinery Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Industrial Machinery Manufacturing"
  },
  {
    "id": "1909",
    "label": "Industry Associations",
    "path": "Consumer Services > Civic and Social Organizations > Industry Associations"
  },
  {
    "id": "84",
    "label": "Information Services",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services"
  },
  {
    "id": "3231",
    "label": "Information Technology and Services",
    "path": "This industry includes entities that provide functions, maintenance, and support for information technology products, or provide services that support the design, development, application, implementation, support, and management of computer-based information systems."
  },
  {
    "id": "42",
    "label": "Insurance",
    "path": "Financial Services > Insurance"
  },
  {
    "id": "1737",
    "label": "Insurance Agencies and Brokerages",
    "path": "Financial Services > Insurance > Insurance Agencies and Brokerages"
  },
  {
    "id": "1743",
    "label": "Insurance and Employee Benefit Funds",
    "path": "Financial Services > Funds and Trusts > Insurance and Employee Benefit Funds"
  },
  {
    "id": "1725",
    "label": "Insurance Carriers",
    "path": "Financial Services > Insurance > Insurance Carriers"
  },
  {
    "id": "3126",
    "label": "Interior Design",
    "path": "Professional Services > Design Services > Interior Design"
  },
  {
    "id": "74",
    "label": "International Affairs",
    "path": "Government Administration > Military and International Affairs > International Affairs"
  },
  {
    "id": "141",
    "label": "International Trade and Development",
    "path": "Financial Services > Credit Intermediation > International Trade and Development"
  },
  {
    "id": "1285",
    "label": "Internet Marketplace Platforms",
    "path": "Technology, Information and Media > Technology, Information and Internet > Internet Marketplace Platforms"
  },
  {
    "id": "3124",
    "label": "Internet News",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services > Internet Publishing > Online Audio and Video Media > Internet News"
  },
  {
    "id": "3132",
    "label": "Internet Publishing",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services > Internet Publishing"
  },
  {
    "id": "1504",
    "label": "Interurban and Rural Bus Services",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation > Interurban and Rural Bus Services"
  },
  {
    "id": "1720",
    "label": "Investment Advice",
    "path": "Financial Services > Capital Markets > Investment Advice"
  },
  {
    "id": "45",
    "label": "Investment Banking",
    "path": "Financial Services > Capital Markets > Investment Banking"
  },
  {
    "id": "46",
    "label": "Investment Management",
    "path": "Financial Services > Capital Markets > Investment Management"
  },
  {
    "id": "96",
    "label": "IT Services and IT Consulting",
    "path": "Professional Services > IT Services and IT Consulting"
  },
  {
    "id": "3102",
    "label": "IT System Custom Software Development",
    "path": "Professional Services > IT Services and IT Consulting > IT System Custom Software Development"
  },
  {
    "id": "3106",
    "label": "IT System Data Services",
    "path": "Professional Services > IT Services and IT Consulting > IT System Data Services"
  },
  {
    "id": "1855",
    "label": "IT System Design Services",
    "path": "Professional Services > IT Services and IT Consulting > IT System Design Services"
  },
  {
    "id": "3104",
    "label": "IT System Installation and Disposal",
    "path": "Professional Services > IT Services and IT Consulting > IT System Installation and Disposal"
  },
  {
    "id": "3103",
    "label": "IT System Operations and Maintenance",
    "path": "Professional Services > IT Services and IT Consulting > IT System Operations and Maintenance"
  },
  {
    "id": "3107",
    "label": "IT System Testing and Evaluation",
    "path": "Professional Services > IT Services and IT Consulting > IT System Testing and Evaluation"
  },
  {
    "id": "3105",
    "label": "IT System Training and Support",
    "path": "Professional Services > IT Services and IT Consulting > IT System Training and Support"
  },
  {
    "id": "1965",
    "label": "Janitorial Services",
    "path": "Administrative and Support Services > Facilities Services > Janitorial Services"
  },
  {
    "id": "2934",
    "label": "Landscaping Services",
    "path": "Administrative and Support Services > Facilities Services > Landscaping Services"
  },
  {
    "id": "2029",
    "label": "Language Schools",
    "path": "Education > Technical and Vocational Training > Language Schools"
  },
  {
    "id": "2272",
    "label": "Laundry and Drycleaning Services",
    "path": "Consumer Services > Personal and Laundry Services > Laundry and Drycleaning Services"
  },
  {
    "id": "77",
    "label": "Law Enforcement",
    "path": "Government Administration > Administration of Justice > Law Enforcement"
  },
  {
    "id": "9",
    "label": "Law Practice",
    "path": "Professional Services > Legal Services > Law Practice"
  },
  {
    "id": "128",
    "label": "Leasing Non-residential Real Estate",
    "path": "Real Estate and Equipment Rental Services > Real Estate > Leasing Non-residential Real Estate"
  },
  {
    "id": "1759",
    "label": "Leasing Residential Real Estate",
    "path": "Real Estate and Equipment Rental Services > Real Estate > Leasing Residential Real Estate"
  },
  {
    "id": "616",
    "label": "Leather Product Manufacturing",
    "path": "Manufacturing > Leather Product Manufacturing"
  },
  {
    "id": "10",
    "label": "Legal Services",
    "path": "Professional Services > Legal Services"
  },
  {
    "id": "72",
    "label": "Legislative Offices",
    "path": "Government Administration > Public Policy Offices > Legislative Offices"
  },
  {
    "id": "3194",
    "label": "Leisure, Travel & Tourism",
    "path": "This industry includes entities that participate in business focused on recreation, entertainment, sports, and tourism-related products and services; and in the business of attracting, accommodating, and entertaining tourists, and the business of operating tours."
  },
  {
    "id": "85",
    "label": "Libraries",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services > Libraries"
  },
  {
    "id": "794",
    "label": "Lime and Gypsum Products Manufacturing",
    "path": "Manufacturing > Glass, Ceramics and Concrete Manufacturing > Lime and Gypsum Products Manufacturing"
  },
  {
    "id": "1696",
    "label": "Loan Brokers",
    "path": "Financial Services > Credit Intermediation > Loan Brokers"
  },
  {
    "id": "3212",
    "label": "Luxury Goods and Jewelry",
    "path": "This industry includes entities that produce and/or sell goods that are not necessary but deemed highly desirable within a culture or society, such as haute couture apparel, fine jewelry and watches, and high-end luggage."
  },
  {
    "id": "55",
    "label": "Machinery Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing"
  },
  {
    "id": "994",
    "label": "Magnetic and Optical Media Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Magnetic and Optical Media Manufacturing"
  },
  {
    "id": "25",
    "label": "Manufacturing",
    "path": "Manufacturing"
  },
  {
    "id": "3236",
    "label": "Maritime",
    "path": "This industry includes entities that participate in the construction, repair, and scraping of watercraft, as well as the movement of cargo and other materials."
  },
  {
    "id": "95",
    "label": "Maritime Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Maritime Transportation"
  },
  {
    "id": "97",
    "label": "Market Research",
    "path": "Professional Services > Advertising Services> Market Research"
  },
  {
    "id": "1862",
    "label": "Marketing Services",
    "path": "Professional Services > Business Consulting and Services > Marketing Services"
  },
  {
    "id": "1095",
    "label": "Mattress and Blinds Manufacturing",
    "path": "Manufacturing > Furniture and Home Furnishings Manufacturing > Mattress and Blinds Manufacturing"
  },
  {
    "id": "983",
    "label": "Measuring and Control Instrument Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Measuring and Control Instrument Manufacturing"
  },
  {
    "id": "521",
    "label": "Meat Products Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Meat Products Manufacturing"
  },
  {
    "id": "3221",
    "label": "Mechanical or Industrial Engineering",
    "path": "This industry includes entities that conduct engineering projects that combine engineering physics and mathematics principles with materials science, to design, analyze, manufacture, and maintain mechanical or industrial systems."
  },
  {
    "id": "3133",
    "label": "Media & Telecommunications",
    "path": "Technology, Information and Media > Media and Telecommunications"
  },
  {
    "id": "126",
    "label": "Media Production",
    "path": "Technology, Information and Media > Media and Telecommunications > Movies, Videos and Sound > Media Production"
  },
  {
    "id": "2069",
    "label": "Medical and Diagnostic Laboratories",
    "path": "Hospitals and Health Care > Medical Practices > Medical and Diagnostic Laboratories"
  },
  {
    "id": "3217",
    "label": "Medical Devices",
    "path": "This industry includes entities that produce and distribute instruments, apparatus, implements, machines, contrivances, implants, in vitro reagents, or other similar products which are intended for use in the diagnosis, mitigation or treatment of disease or other medical conditions."
  },
  {
    "id": "17",
    "label": "Medical Equipment Manufacturing",
    "path": "Manufacturing > Medical Equipment Manufacturing"
  },
  {
    "id": "13",
    "label": "Medical Practices",
    "path": "Hospitals and Health Care > Medical Practices"
  },
  {
    "id": "139",
    "label": "Mental Health Care",
    "path": "Hospitals and Health Care > Medical Practices > Mental Health Care"
  },
  {
    "id": "345",
    "label": "Metal Ore Mining",
    "path": "Oil, Gas, and Mining > Mining > Metal Ore Mining"
  },
  {
    "id": "883",
    "label": "Metal Treatments",
    "path": "Manufacturing > Fabricated Metal Products > Metal Treatments"
  },
  {
    "id": "887",
    "label": "Metal Valve, Ball, and Roller Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Metal Valve, Ball, and Roller Manufacturing"
  },
  {
    "id": "928",
    "label": "Metalworking Machinery Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Metalworking Machinery Manufacturing"
  },
  {
    "id": "2391",
    "label": "Military and International Affairs",
    "path": "Government Administration > Military and International Affairs"
  },
  {
    "id": "56",
    "label": "Mining",
    "path": "Oil, Gas, and Mining > Mining"
  },
  {
    "id": "3100",
    "label": "Mobile Computing Software Products",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Mobile Computing Software Products"
  },
  {
    "id": "2214",
    "label": "Mobile Food Services",
    "path": "Accommodation Services > Food and Beverage Services > Mobile Food Services"
  },
  {
    "id": "3131",
    "label": "Mobile Gaming Apps",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development > Computer Games > Mobile Gaming Apps"
  },
  {
    "id": "53",
    "label": "Motor Vehicle Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Motor Vehicle Manufacturing"
  },
  {
    "id": "1042",
    "label": "Motor Vehicle Parts Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Motor Vehicle Parts Manufacturing"
  },
  {
    "id": "1611",
    "label": "Movies and Sound Recording",
    "path": "Technology, Information and Media > Media and Telecommunications > Movies, Videos and Sound > Movies and Sound Recording"
  },
  {
    "id": "35",
    "label": "Movies, Videos and Sound",
    "path": "Technology, Information and Media > Media and Telecommunications > Movies, Videos and Sound"
  },
  {
    "id": "2159",
    "label": "Museums",
    "path": "Entertainment Providers > Museums, Historical Sites, and Zoos > Museums"
  },
  {
    "id": "37",
    "label": "Museums, Historical Sites, and Zoos",
    "path": "Entertainment Providers > Museums, Historical Sites, and Zoos"
  },
  {
    "id": "3205",
    "label": "Music",
    "path": "This industry includes entities that are involved in music creation, performance, and distribution."
  },
  {
    "id": "115",
    "label": "Musicians",
    "path": "Entertainment Providers > Musicians"
  },
  {
    "id": "114",
    "label": "Nanotechnology Research",
    "path": "Professional Services > Research Services > Nanotechnology Research"
  },
  {
    "id": "397",
    "label": "Natural Gas Distribution",
    "path": "Utilities > Natural Gas Distribution"
  },
  {
    "id": "3096",
    "label": "Natural Gas Extraction",
    "path": "Oil, Gas, and Mining > Oil and Gas > Natural Gas Extraction"
  },
  {
    "id": "81",
    "label": "Newspaper Publishing",
    "path": "Technology, Information and Media > Media and Telecommunications > Book and Periodical Publishing > Newspaper Publishing"
  },
  {
    "id": "3202",
    "label": "Non-profit Organization Management",
    "path": "This industry includes entities that participate in the administration and management of a not-for-profit organization."
  },
  {
    "id": "100",
    "label": "Non-profit Organizations",
    "path": "Consumer Services > Non-profit Organizations"
  },
  {
    "id": "356",
    "label": "Nonmetallic Mineral Mining",
    "path": "Oil, Gas, and Mining > Mining > Nonmetallic Mineral Mining"
  },
  {
    "id": "413",
    "label": "Nonresidential Building Construction",
    "path": "Construction > Building Construction > Nonresidential Building Construction"
  },
  {
    "id": "386",
    "label": "Nuclear Electric Power Generation",
    "path": "Utilities > Electric Power Generation > Nuclear Electric Power Generation"
  },
  {
    "id": "2091",
    "label": "Nursing Homes and Residential Care Facilities",
    "path": "Hospitals and Health Care > Nursing Homes and Residential Care Facilities"
  },
  {
    "id": "1916",
    "label": "Office Administration",
    "path": "Administrative and Support Services > Office Administration"
  },
  {
    "id": "1090",
    "label": "Office Furniture and Fixtures Manufacturing",
    "path": "Manufacturing > Furniture and Home Furnishings Manufacturing > Office Furniture and Fixtures Manufacturing"
  },
  {
    "id": "679",
    "label": "Oil and Coal Product Manufacturing",
    "path": "Manufacturing > Oil and Coal Product Manufacturing"
  },
  {
    "id": "57",
    "label": "Oil and Gas",
    "path": "Oil, Gas, and Mining > Oil and Gas"
  },
  {
    "id": "3095",
    "label": "Oil Extraction",
    "path": "Oil, Gas, and Mining > Oil and Gas > Oil Extraction"
  },
  {
    "id": "332",
    "label": "Oil, Gas, and Mining",
    "path": "Oil, Gas, and Mining"
  },
  {
    "id": "1445",
    "label": "Online and Mail Order Retail",
    "path": "Retail > Online and Mail Order Retail"
  },
  {
    "id": "113",
    "label": "Online Audio and Video Media",
    "path": "Technology, Information and Media > Technology, Information and Internet > Information Services > Internet Publishing > Online Audio and Video Media"
  },
  {
    "id": "3214",
    "label": "Online Media",
    "path": "This industry includes entities that produce and/or distribute media, which is published over the Internet, and includes, without limitation, web-sites, blogs, and social media."
  },
  {
    "id": "2401",
    "label": "Operations Consulting",
    "path": "Professional Services > Business Consulting and Services > Operations Consulting"
  },
  {
    "id": "2050",
    "label": "Optometrists",
    "path": "Hospitals and Health Care > Medical Practices > Optometrists"
  },
  {
    "id": "2063",
    "label": "Outpatient Care Centers",
    "path": "Hospitals and Health Care > Medical Practices > Outpatient Care Centers"
  },
  {
    "id": "123",
    "label": "Outsourcing and Offshoring Consulting",
    "path": "Professional Services > Business Consulting and Services > Outsourcing and Offshoring Consulting"
  },
  {
    "id": "3206",
    "label": "Outsourcing/Offshoring",
    "path": "This industry includes entities that negotiate contracts with a third party to perform a specific function and/or send in-house jobs to be performed in another country/region."
  },
  {
    "id": "3223",
    "label": "Packaging and Containers",
    "path": "This industry includes entities that carry out the planning, creating, manufacturing, wrapping, boxing, or bottling of goods."
  },
  {
    "id": "146",
    "label": "Packaging and Containers Manufacturing",
    "path": "Manufacturing > Plastics and Rubber Product Manufacturing > Packaging and Containers Manufacturing"
  },
  {
    "id": "722",
    "label": "Paint, Coating, and Adhesive Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Paint, Coating, and Adhesive Manufacturing"
  },
  {
    "id": "61",
    "label": "Paper and Forest Product Manufacturing",
    "path": "Manufacturing > Paper and Forest Product Manufacturing"
  },
  {
    "id": "3239",
    "label": "Paper and Forest Products",
    "path": "This industry includes entities that produce and/or sell any material derived from forestry for direct consumption or commercial use, such as lumber, paper, or fodder for livestock."
  },
  {
    "id": "1745",
    "label": "Pension Funds",
    "path": "Financial Services > Funds and Trusts > Pension Funds"
  },
  {
    "id": "39",
    "label": "Performing Arts",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Performing Arts"
  },
  {
    "id": "2130",
    "label": "Performing Arts and Spectator Sports",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports"
  },
  {
    "id": "1600",
    "label": "Periodical Publishing",
    "path": "Technology, Information and Media > Media and Telecommunications > Book and Periodical Publishing > Periodical Publishing"
  },
  {
    "id": "2258",
    "label": "Personal and Laundry Services",
    "path": "Consumer Services > Personal and Laundry Services"
  },
  {
    "id": "18",
    "label": "Personal Care Product Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Personal Care Product Manufacturing"
  },
  {
    "id": "2259",
    "label": "Personal Care Services",
    "path": "Consumer Services > Personal and Laundry Services > Personal Care Services"
  },
  {
    "id": "2282",
    "label": "Pet Services",
    "path": "Consumer Services > Personal and Laundry Services > Pet Services"
  },
  {
    "id": "15",
    "label": "Pharmaceutical Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Pharmaceutical Manufacturing"
  },
  {
    "id": "131",
    "label": "Philanthropic Fundraising Services",
    "path": "Consumer Services > Philanthropic Fundraising Services"
  },
  {
    "id": "3230",
    "label": "Philanthropy",
    "path": "This industry includes entities that participate in charitable giving, for the public good, focusing on quality of life."
  },
  {
    "id": "136",
    "label": "Photography",
    "path": "Professional Services > Photography"
  },
  {
    "id": "2054",
    "label": "Physical, Occupational and Speech Therapists",
    "path": "Hospitals and Health Care > Medical Practices > Physical, Occupational and Speech Therapists"
  },
  {
    "id": "2040",
    "label": "Physicians",
    "path": "Hospitals and Health Care > Medical Practices > Physicians"
  },
  {
    "id": "1520",
    "label": "Pipeline Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Pipeline Transportation"
  },
  {
    "id": "743",
    "label": "Plastics and Rubber Product Manufacturing",
    "path": "Manufacturing > Plastics and Rubber Product Manufacturing"
  },
  {
    "id": "117",
    "label": "Plastics Manufacturing",
    "path": "Manufacturing > Plastics and Rubber Product Manufacturing > Plastics Manufacturing"
  },
  {
    "id": "107",
    "label": "Political Organizations",
    "path": "Consumer Services > Civic and Social Organizations > Political Organizations"
  },
  {
    "id": "1573",
    "label": "Postal Services",
    "path": "Transportation, Logistics, Supply Chain and Storage > Postal Services"
  },
  {
    "id": "67",
    "label": "Primary and Secondary Education",
    "path": "Education > Primary and Secondary Education"
  },
  {
    "id": "807",
    "label": "Primary Metal Manufacturing",
    "path": "Manufacturing > Primary Metal Manufacturing"
  },
  {
    "id": "83",
    "label": "Printing Services",
    "path": "Manufacturing > Printing Services"
  },
  {
    "id": "1911",
    "label": "Professional Organizations",
    "path": "Consumer Services > Civic and Social Organizations > Professional Organizations"
  },
  {
    "id": "1810",
    "label": "Professional Services",
    "path": "Professional Services"
  },
  {
    "id": "105",
    "label": "Professional Training and Coaching",
    "path": "Education > Professional Training and Coaching"
  },
  {
    "id": "3203",
    "label": "Program Development",
    "path": "This industry includes entities that participate in the ongoing systematic process of planning, implementing and evaluating programs."
  },
  {
    "id": "2360",
    "label": "Public Assistance Programs",
    "path": "Government Administration > Health and Human Services > Public Assistance Programs"
  },
  {
    "id": "2358",
    "label": "Public Health",
    "path": "Government Administration > Health and Human Services > Public Health"
  },
  {
    "id": "3201",
    "label": "Public Policy",
    "path": "This industry includes entities that participate in programs as a course of action created and/or enacted, typically by a government or nonprofit organization, in response to social issues."
  },
  {
    "id": "79",
    "label": "Public Policy Offices",
    "path": "Government Administration > Public Policy Offices"
  },
  {
    "id": "98",
    "label": "Public Relations and Communications Services",
    "path": "Professional Services > Advertising Services > Public Relations and Communications Services"
  },
  {
    "id": "78",
    "label": "Public Safety",
    "path": "Government Administration > Administration of Justice > Public Safety"
  },
  {
    "id": "2143",
    "label": "Racetracks",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Spectator Sports > Racetracks"
  },
  {
    "id": "1633",
    "label": "Radio and Television Broadcasting",
    "path": "Technology, Information and Media > Media and Telecommunications > Broadcast Media Production and Distribution > Radio and Television Broadcasting"
  },
  {
    "id": "1481",
    "label": "Rail Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Rail Transportation"
  },
  {
    "id": "62",
    "label": "Railroad Equipment Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Railroad Equipment Manufacturing"
  },
  {
    "id": "64",
    "label": "Ranching",
    "path": "Farming, Ranching, Forestry > Ranching and Fisheries > Ranching"
  },
  {
    "id": "256",
    "label": "Ranching and Fisheries",
    "path": "Farming, Ranching, Forestry > Ranching and Fisheries"
  },
  {
    "id": "44",
    "label": "Real Estate",
    "path": "Real Estate and Equipment Rental Services > Real Estate"
  },
  {
    "id": "1770",
    "label": "Real Estate Agents and Brokers",
    "path": "Real Estate and Equipment Rental Services > Real Estate > Real Estate Agents and Brokers"
  },
  {
    "id": "1757",
    "label": "Real Estate and Equipment Rental Services",
    "path": "Real Estate and Equipment Rental Services"
  },
  {
    "id": "40",
    "label": "Recreational Facilities",
    "path": "Entertainment Providers > Recreational Facilities"
  },
  {
    "id": "3256",
    "label": "Regenerative Design",
    "path": "Professional Services > Design Services > Regenerative Design"
  },
  {
    "id": "89",
    "label": "Religious Institutions",
    "path": "Consumer Services > Religious Institutions"
  },
  {
    "id": "3241",
    "label": "Renewable Energy Equipment Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Engines and Power Transmission Equipment Manufacturing > Renewable Energy Equipment Manufacturing"
  },
  {
    "id": "3240",
    "label": "Renewable Energy Power Generation",
    "path": "Utilities > Electric Power Generation > Renewable Energy Power Generation"
  },
  {
    "id": "144",
    "label": "Renewable Energy Semiconductor Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Semiconductor Manufacturing > Renewable Energy Semiconductor Manufacturing"
  },
  {
    "id": "3213",
    "label": "Renewables & Environment",
    "path": "This industry includes entities that are part of the energy industry focused on new and appropriate renewable energy technologies."
  },
  {
    "id": "2225",
    "label": "Repair and Maintenance",
    "path": "Consumer Services > Repair and Maintenance"
  },
  {
    "id": "3233",
    "label": "Research",
    "path": "This industry includes entities that provide systematic investigation into and study of materials and sources in order to establish facts and reach new conclusions."
  },
  {
    "id": "70",
    "label": "Research Services",
    "path": "Professional Services > Research Services"
  },
  {
    "id": "408",
    "label": "Residential Building Construction",
    "path": "Construction > Building Construction > Residential Building Construction"
  },
  {
    "id": "32",
    "label": "Restaurants",
    "path": "Accommodation Services > Food and Beverage Services > Restaurants"
  },
  {
    "id": "27",
    "label": "Retail",
    "path": "Retail"
  },
  {
    "id": "19",
    "label": "Retail Apparel and Fashion",
    "path": "Retail > Retail Apparel and Fashion"
  },
  {
    "id": "1319",
    "label": "Retail Appliances, Electrical, and Electronic Equipment",
    "path": "Retail > Retail Appliances, Electrical, and Electronic Equipment"
  },
  {
    "id": "3186",
    "label": "Retail Art Dealers",
    "path": "Retail > Retail Art Dealers"
  },
  {
    "id": "111",
    "label": "Retail Art Supplies",
    "path": "Retail > Retail Art Supplies"
  },
  {
    "id": "1409",
    "label": "Retail Books and Printed News",
    "path": "Retail > Retail Books and Printed News"
  },
  {
    "id": "1324",
    "label": "Retail Building Materials and Garden Equipment",
    "path": "Retail > Retail Building Materials and Garden Equipment"
  },
  {
    "id": "1423",
    "label": "Retail Florists",
    "path": "Retail > Retail Florists"
  },
  {
    "id": "1309",
    "label": "Retail Furniture and Home Furnishings",
    "path": "Retail > Retail Furniture and Home Furnishings"
  },
  {
    "id": "1370",
    "label": "Retail Gasoline",
    "path": "Retail > Retail Gasoline"
  },
  {
    "id": "22",
    "label": "Retail Groceries",
    "path": "Retail > Food and Beverage Retail > Retail Groceries"
  },
  {
    "id": "1359",
    "label": "Retail Health and Personal Care Products",
    "path": "Retail > Retail Health and Personal Care Products"
  },
  {
    "id": "143",
    "label": "Retail Luxury Goods and Jewelry",
    "path": "Retail > Retail Luxury Goods and Jewelry"
  },
  {
    "id": "1292",
    "label": "Retail Motor Vehicles",
    "path": "Retail > Retail Motor Vehicles"
  },
  {
    "id": "1407",
    "label": "Retail Musical Instruments",
    "path": "Retail > Retail Musical Instruments"
  },
  {
    "id": "138",
    "label": "Retail Office Equipment",
    "path": "Retail > Retail Office Equipment"
  },
  {
    "id": "1424",
    "label": "Retail Office Supplies and Gifts",
    "path": "Retail > Retail Office Supplies and Gifts"
  },
  {
    "id": "3250",
    "label": "Retail Pharmacies",
    "path": "Retail > Retail Health and Personal Care Products > Retail Pharmacies"
  },
  {
    "id": "1431",
    "label": "Retail Recyclable Materials & Used Merchandise",
    "path": "Retail > Retail Recyclable Materials & Used Merchandise"
  },
  {
    "id": "2253",
    "label": "Reupholstery and Furniture Repair",
    "path": "Consumer Services > Repair and Maintenance > Reupholstery and Furniture Repair"
  },
  {
    "id": "3247",
    "label": "Robot Manufacturing",
    "path": "Manufacturing > Machinery Manufacturing > Automation Machinery Manufacturing > Robot Manufacturing"
  },
  {
    "id": "3248",
    "label": "Robotics Engineering",
    "path": "Professional Services > Engineering Services > Robotics Engineering"
  },
  {
    "id": "763",
    "label": "Rubber Products Manufacturing",
    "path": "Manufacturing > Plastics and Rubber Product Manufacturing > Rubber Products Manufacturing"
  },
  {
    "id": "1649",
    "label": "Satellite Telecommunications",
    "path": "Technology, Information and Media > Media and Telecommunications > Telecommunications > Satellite Telecommunications"
  },
  {
    "id": "1678",
    "label": "Savings Institutions",
    "path": "Financial Services > Credit Intermediation > Savings Institutions"
  },
  {
    "id": "1512",
    "label": "School and Employee Bus Services",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation > School and Employee Bus Services"
  },
  {
    "id": "528",
    "label": "Seafood Product Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Seafood Product Manufacturing"
  },
  {
    "id": "2012",
    "label": "Secretarial Schools",
    "path": "Education > Technical and Vocational Training > Secretarial Schools"
  },
  {
    "id": "1713",
    "label": "Securities and Commodity Exchanges",
    "path": "Financial Services > Capital Markets > Securities and Commodity Exchanges"
  },
  {
    "id": "121",
    "label": "Security and Investigations",
    "path": "Administrative and Support Services > Security and Investigations"
  },
  {
    "id": "1956",
    "label": "Security Guards and Patrol Services",
    "path": "Administrative and Support Services > Security and Investigations > Security Guards and Patrol Services"
  },
  {
    "id": "1958",
    "label": "Security Systems Services",
    "path": "Administrative and Support Services > Security and Investigations > Security Systems Services"
  },
  {
    "id": "7",
    "label": "Semiconductor Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Semiconductor Manufacturing"
  },
  {
    "id": "3218",
    "label": "Semiconductors",
    "path": "This industry includes entities that produce and/or sell semiconductors."
  },
  {
    "id": "3243",
    "label": "Services for Renewable Energy",
    "path": "Professional Services > Services for Renewable Energy"
  },
  {
    "id": "2112",
    "label": "Services for the Elderly and Disabled",
    "path": "Hospitals and Health Care > Community Services > Services for the Elderly and Disabled"
  },
  {
    "id": "1625",
    "label": "Sheet Music Publishing",
    "path": "Technology, Information and Media > Media and Telecommunications > Movies, Videos and Sound > Sheet Music Publishing"
  },
  {
    "id": "58",
    "label": "Shipbuilding",
    "path": "Manufacturing > Transportation Equipment Manufacturing > Shipbuilding"
  },
  {
    "id": "1517",
    "label": "Shuttles and Special Needs Transportation Services",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation > Shuttles and Special Needs Transportation Services"
  },
  {
    "id": "1532",
    "label": "Sightseeing Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation > Sightseeing Transportation"
  },
  {
    "id": "2181",
    "label": "Skiing Facilities",
    "path": "Entertainment Providers > Recreational Facilities > Skiing Facilities"
  },
  {
    "id": "3254",
    "label": "Smart Meter Manufacturing",
    "path": "Manufacturing > Computers and Electronics Manufacturing > Measuring and Control Instrument Manufacturing > Smart Meter Manufacturing"
  },
  {
    "id": "727",
    "label": "Soap and Cleaning Product Manufacturing",
    "path": "Manufacturing > Chemical Manufacturing > Soap and Cleaning Product Manufacturing"
  },
  {
    "id": "3127",
    "label": "Social Networking Platforms",
    "path": "Technology, Information and Media > Technology, Information and Internet > Social Networking Platforms"
  },
  {
    "id": "4",
    "label": "Software Development",
    "path": "Technology, Information and Media > Technology, Information and Internet > Software Development"
  },
  {
    "id": "387",
    "label": "Solar Electric Power Generation",
    "path": "Utilities > Electric Power Generation > Renewable Energy Power Generation > Solar Electric Power Generation"
  },
  {
    "id": "1623",
    "label": "Sound Recording",
    "path": "Technology, Information and Media > Media and Telecommunications > Movies, Videos and Sound > Movies and Sound Recording > Sound Recording"
  },
  {
    "id": "3089",
    "label": "Space Research and Technology",
    "path": "Government Administration > Space Research and Technology"
  },
  {
    "id": "435",
    "label": "Specialty Trade Contractors",
    "path": "Construction > Specialty Trade Contractors"
  },
  {
    "id": "33",
    "label": "Spectator Sports",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Spectator Sports"
  },
  {
    "id": "3225",
    "label": "Sporting Goods",
    "path": "This industry includes entities that produce and/or sell the equipment, materials, apparel, and gear used to participate in a sport."
  },
  {
    "id": "20",
    "label": "Sporting Goods Manufacturing",
    "path": "Manufacturing > Sporting Goods Manufacturing"
  },
  {
    "id": "2027",
    "label": "Sports and Recreation Instruction",
    "path": "Education > Technical and Vocational Training > Sports and Recreation Instruction"
  },
  {
    "id": "2142",
    "label": "Sports Teams and Clubs",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Spectator Sports > Sports Teams and Clubs"
  },
  {
    "id": "873",
    "label": "Spring and Wire Product Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Spring and Wire Product Manufacturing"
  },
  {
    "id": "104",
    "label": "Staffing and Recruiting",
    "path": "Administrative and Support Services > Staffing and Recruiting"
  },
  {
    "id": "404",
    "label": "Steam and Air-Conditioning Supply",
    "path": "Utilities > Water, Waste, Steam, and Air Conditioning Services > Steam and Air-Conditioning Supply"
  },
  {
    "id": "102",
    "label": "Strategic Management Services",
    "path": "Professional Services > Business Consulting and Services > Strategic Management Services"
  },
  {
    "id": "428",
    "label": "Subdivision of Land",
    "path": "Construction > Civil Engineering > Subdivision of Land"
  },
  {
    "id": "495",
    "label": "Sugar and Confectionery Product Manufacturing",
    "path": "Manufacturing > Food and Beverage Manufacturing > Sugar and Confectionery Product Manufacturing"
  },
  {
    "id": "3249",
    "label": "Surveying and Mapping Services",
    "path": "Professional Services > Engineering Services > Surveying and Mapping Services"
  },
  {
    "id": "1505",
    "label": "Taxi and Limousine Services",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation > Taxi and Limousine Services"
  },
  {
    "id": "2018",
    "label": "Technical and Vocational Training",
    "path": "Education > Technical and Vocational Training"
  },
  {
    "id": "6",
    "label": "Technology, Information and Internet",
    "path": "Technology, Information and Media > Technology, Information and Internet"
  },
  {
    "id": "1594",
    "label": "Technology, Information and Media",
    "path": "Technology, Information and Media"
  },
  {
    "id": "8",
    "label": "Telecommunications",
    "path": "Technology, Information and Media > Media and Telecommunications > Telecommunications"
  },
  {
    "id": "1644",
    "label": "Telecommunications Carriers",
    "path": "Technology, Information and Media > Media and Telecommunications > Telecommunications > Telecommunications Carriers"
  },
  {
    "id": "1931",
    "label": "Telephone Call Centers",
    "path": "Administrative and Support Services > Telephone Call Centers"
  },
  {
    "id": "1925",
    "label": "Temporary Help Services",
    "path": "Administrative and Support Services > Staffing and Recruiting > Temporary Help Services"
  },
  {
    "id": "60",
    "label": "Textile Manufacturing",
    "path": "Manufacturing > Textile Manufacturing"
  },
  {
    "id": "2133",
    "label": "Theater Companies",
    "path": "Entertainment Providers > Performing Arts and Spectator Sports > Theater Companies"
  },
  {
    "id": "130",
    "label": "Think Tanks",
    "path": "Professional Services > Research Services > Think Tanks"
  },
  {
    "id": "3228",
    "label": "Tobacco",
    "path": "This industry includes entities that produce and/or sell tobacco and tobacco-related products"
  },
  {
    "id": "21",
    "label": "Tobacco Manufacturing",
    "path": "Manufacturing > Tobacco Manufacturing"
  },
  {
    "id": "108",
    "label": "Translation and Localization",
    "path": "Administrative and Support Services > Translation and Localization"
  },
  {
    "id": "1029",
    "label": "Transportation Equipment Manufacturing",
    "path": "Manufacturing > Transportation Equipment Manufacturing"
  },
  {
    "id": "3085",
    "label": "Transportation Programs",
    "path": "Government Administration > Economic Programs > Transportation Programs"
  },
  {
    "id": "116",
    "label": "Transportation, Logistics, Supply Chain and Storage",
    "path": "Transportation, Logistics, Supply Chain and Storage"
  },
  {
    "id": "3222",
    "label": "Transportation/Trucking/Railroad",
    "path": "This industry includes entities that provide services for moving people, goods, or the infrastructure to do so."
  },
  {
    "id": "30",
    "label": "Travel Arrangements",
    "path": "Administrative and Support Services > Travel Arrangements"
  },
  {
    "id": "92",
    "label": "Truck Transportation",
    "path": "Transportation, Logistics, Supply Chain and Storage > Truck Transportation"
  },
  {
    "id": "1750",
    "label": "Trusts and Estates",
    "path": "Financial Services > Funds and Trusts > Trusts and Estates"
  },
  {
    "id": "876",
    "label": "Turned Products and Fastener Manufacturing",
    "path": "Manufacturing > Fabricated Metal Products > Turned Products and Fastener Manufacturing"
  },
  {
    "id": "1497",
    "label": "Urban Transit Services",
    "path": "Transportation, Logistics, Supply Chain and Storage > Ground Passenger Transportation > Urban Transit Services"
  },
  {
    "id": "59",
    "label": "Utilities",
    "path": "Utilities"
  },
  {
    "id": "3086",
    "label": "Utilities Administration",
    "path": "Government Administration > Economic Programs > Utilities Administration"
  },
  {
    "id": "419",
    "label": "Utility System Construction",
    "path": "Construction > Civil Engineering > Utility System Construction"
  },
  {
    "id": "2226",
    "label": "Vehicle Repair and Maintenance",
    "path": "Consumer Services > Repair and Maintenance > Vehicle Repair and Maintenance"
  },
  {
    "id": "106",
    "label": "Venture Capital and Private Equity Principals",
    "path": "Financial Services > Capital Markets > Venture Capital and Private Equity Principals"
  },
  {
    "id": "3188",
    "label": "Veterinary",
    "path": "This industry includes entities that participate in economic activities related to the practice of veterinary medicine, dentistry, or surgery for animals."
  },
  {
    "id": "16",
    "label": "Veterinary Services",
    "path": "Professional Services > Veterinary Services"
  },
  {
    "id": "2125",
    "label": "Vocational Rehabilitation Services",
    "path": "Hospitals and Health Care > Individual and Family Services > Vocational Rehabilitation Services"
  },
  {
    "id": "3229",
    "label": "Warehousing",
    "path": "This industry includes entities that provide storage of physical inventory for sale or distribution."
  },
  {
    "id": "93",
    "label": "Warehousing and Storage",
    "path": "Transportation, Logistics, Supply Chain and Storage > Warehousing and Storage"
  },
  {
    "id": "1981",
    "label": "Waste Collection",
    "path": "Utilities > Water, Waste, Steam, and Air Conditioning Services > Waste Collection"
  },
  {
    "id": "1986",
    "label": "Waste Treatment and Disposal",
    "path": "Utilities > Water, Waste, Steam, and Air Conditioning Services > Waste Treatment and Disposal"
  },
  {
    "id": "400",
    "label": "Water Supply and Irrigation Systems",
    "path": "Utilities > Water, Waste, Steam, and Air Conditioning Services > Water Supply and Irrigation Systems"
  },
  {
    "id": "398",
    "label": "Water, Waste, Steam, and Air Conditioning Services",
    "path": "Utilities > Water, Waste, Steam, and Air Conditioning Services"
  },
  {
    "id": "124",
    "label": "Wellness and Fitness Services",
    "path": "Entertainment Providers > Recreational Facilities > Wellness and Fitness Services"
  },
  {
    "id": "133",
    "label": "Wholesale",
    "path": "Wholesale"
  },
  {
    "id": "1267",
    "label": "Wholesale Alcoholic Beverages",
    "path": "Wholesale > Wholesale Alcoholic Beverages"
  },
  {
    "id": "1222",
    "label": "Wholesale Apparel and Sewing Supplies",
    "path": "Wholesale > Wholesale Apparel and Sewing Supplies"
  },
  {
    "id": "1171",
    "label": "Wholesale Appliances, Electrical, and Electronics",
    "path": "Wholesale > Wholesale Appliances, Electrical, and Electronics"
  },
  {
    "id": "49",
    "label": "Wholesale Building Materials",
    "path": "Wholesale > Wholesale Building Materials"
  },
  {
    "id": "1257",
    "label": "Wholesale Chemical and Allied Products",
    "path": "Wholesale > Wholesale Chemical and Allied Products"
  },
  {
    "id": "1157",
    "label": "Wholesale Computer Equipment",
    "path": "Wholesale > Wholesale Computer Equipment"
  },
  {
    "id": "1221",
    "label": "Wholesale Drugs and Sundries",
    "path": "Wholesale > Wholesale Drugs and Sundries"
  },
  {
    "id": "1231",
    "label": "Wholesale Food and Beverage",
    "path": "Wholesale > Wholesale Food and Beverage"
  },
  {
    "id": "1230",
    "label": "Wholesale Footwear",
    "path": "Wholesale > Wholesale Footwear"
  },
  {
    "id": "1137",
    "label": "Wholesale Furniture and Home Furnishings",
    "path": "Wholesale > Wholesale Furniture and Home Furnishings"
  },
  {
    "id": "1178",
    "label": "Wholesale Hardware, Plumbing, Heating Equipment",
    "path": "Wholesale > Wholesale Hardware, Plumbing, Heating Equipment"
  },
  {
    "id": "134",
    "label": "Wholesale Import and Export",
    "path": "Wholesale > Wholesale Import and Export"
  },
  {
    "id": "1208",
    "label": "Wholesale Luxury Goods and Jewelry",
    "path": "Wholesale > Wholesale Luxury Goods and Jewelry"
  },
  {
    "id": "1187",
    "label": "Wholesale Machinery",
    "path": "Wholesale > Wholesale Machinery"
  },
  {
    "id": "1166",
    "label": "Wholesale Metals and Minerals",
    "path": "Wholesale > Wholesale Metals and Minerals"
  },
  {
    "id": "1128",
    "label": "Wholesale Motor Vehicles and Parts",
    "path": "Wholesale > Wholesale Motor Vehicles and Parts"
  },
  {
    "id": "1212",
    "label": "Wholesale Paper Products",
    "path": "Wholesale > Wholesale Paper Products"
  },
  {
    "id": "1262",
    "label": "Wholesale Petroleum and Petroleum Products",
    "path": "Wholesale > Wholesale Petroleum and Petroleum Products"
  },
  {
    "id": "1153",
    "label": "Wholesale Photography Equipment and Supplies",
    "path": "Wholesale > Wholesale Photography Equipment and Supplies"
  },
  {
    "id": "1250",
    "label": "Wholesale Raw Farm Products",
    "path": "Wholesale > Wholesale Raw Farm Products"
  },
  {
    "id": "1206",
    "label": "Wholesale Recyclable Materials",
    "path": "Wholesale > Wholesale Recyclable Materials"
  },
  {
    "id": "2489",
    "label": "Wind Electric Power Generation",
    "path": "Utilities > Electric Power Generation > Renewable Energy Power Generation > Wind Electric Power Generation"
  },
  {
    "id": "3220",
    "label": "Wine and Spirits",
    "path": "This industry includes entities that produce and/or sell alcoholic drinks exclusive of beer and cider."
  },
  {
    "id": "2500",
    "label": "Wineries",
    "path": "Manufacturing > Food and Beverage Manufacturing > > Wineries"
  },
  {
    "id": "119",
    "label": "Wireless Services",
    "path": "Technology, Information and Media > Media and Telecommunications > Telecommunications > Wireless Services"
  },
  {
    "id": "625",
    "label": "Women's Handbag Manufacturing",
    "path": "Manufacturing > Leather Product Manufacturing > Women's Handbag Manufacturing"
  },
  {
    "id": "784",
    "label": "Wood Product Manufacturing",
    "path": "Manufacturing > Wood Product Manufacturing"
  },
  {
    "id": "103",
    "label": "Writing and Editing",
    "path": "Administrative and Support Services > Writing and Editing"
  },
  {
    "id": "2163",
    "label": "Zoos and Botanical Gardens",
    "path": "Entertainment Providers > Museums, Historical Sites, and Zoos > Zoos and Botanical Gardens"
  }
];

export const INDUSTRY_BY_ID: ReadonlyMap<string, LinkedInIndustry> = new Map(
  LINKEDIN_INDUSTRIES.map((i) => [i.id, i])
);
